User.delete_all
Quote.delete_all
Favorite.delete_all

Quote.create(quote_text: "Believe you can and you're halfway there.")
Quote.create(quote_text: "Be more concerned with your character than with your reputation. Your character is what you really are, while your reputation is merely what others think you are.")
Quote.create(quote_text: "Change your thoughts and you change your world.")
Quote.create(quote_text: "Success is never final. Failure is never fatal. It is courage that counts.")
Quote.create(quote_text: "What You Lack In Talent Can Be Made Up With Desire, Hustle And Giving 110% All The Time.")
Quote.create(quote_text: "Out of clutter, find Simplicity. From discord, find Harmony. In the middle of difficulty lies Opportunity.")
Quote.create(quote_text: "Belief creates the actual fact.")
Quote.create(quote_text: "Don't judge each day by the harvest you reap but by the seeds that you plant.")
Quote.create(quote_text: "The best way out is always through.")
Quote.create(quote_text: "With self-discipline most anything is possible.")
Quote.create(quote_text: "Even if you’re on the right track, you’ll get run over if you just sit there.")
Quote.create(quote_text: "When I hear somebody sigh, ‘Life is hard,’ I am always tempted to ask, ‘Compared to what")
Quote.create(quote_text: "Nurture your mind with great thoughts. To believe in the heroic makes heroes")
Quote.create(quote_text: "The real opportunity for success lies within the person and not in the job.")
Quote.create(quote_text: "Look at the sparrows; they do not know what they will do in the next moment. Let us literally live from moment to moment")
Quote.create(quote_text: "Luck is a dividend of sweat. The more you sweat, the luckier you get.")
Quote.create(quote_text: "When I let go of what I am, I become what I might be.")
Quote.create(quote_text: "Whoever loves much, performs much, and can accomplish much, and what is done in love is done well.")
Quote.create(quote_text: "The Pessimist Sees Difficulty In Every Opportunity. The Optimist Sees Opportunity In Every Difficulty.")
Quote.create(quote_text: "Don’t Let Yesterday Take Up Too Much Of Today.")
Quote.create(quote_text: "You Learn More From Failure Than From Success. Don’t Let It Stop You. Failure Builds Character.")
Quote.create(quote_text: "It’s Not Whether You Get Knocked Down, It’s Whether You Get Up.")
Quote.create(quote_text: "If You Are Working On Something That You Really Care About, You Don’t Have To Be Pushed. The Vision Pulls You.")
Quote.create(quote_text: "People Who Are Crazy Enough To Think They Can Change The World, Are The Ones Who Do.")
Quote.create(quote_text: "We May Encounter Many Defeats But We Must Not Be Defeated.")
Quote.create(quote_text: "We Generate Fears While We Sit. We Overcome Them By Action.")
Quote.create(quote_text: "Whether You Think You Can Or Think You Can’t, You’re Right.")
Quote.create(quote_text: "Security Is Mostly A Superstition. Life Is Either A Daring Adventure Or Nothing.")
Quote.create(quote_text: "The Man Who Has Confidence In Himself Gains The Confidence Of Others.")
Quote.create(quote_text: "The Only Limit To Our Realization Of Tomorrow Will Be Our Doubts Of Today.")
